services:

  mysql:
    image: mysql:8
    restart: always
    container_name: springerp-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: springerp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - erp-network

  app:
    build: .
    container_name: springerp-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springerp?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - erp-network

volumes:
  mysql-data:

networks:
  erp-network:
    driver: bridge
